---
defaults:
  admins: &1
    class_name: all
    email: mytea@world.com
    phone: '15859859888'
    password: myteaworld
  users: &2
    class_name: User
    opening: 0
    pending: 1
    rejected: 2
    passed: 3
    opening_title: 新用户
    pending_title: 待审核
    rejected_title: 不通过
    passed_title: 通过
    phone: 电话
    password: 密码
    password_confirmation: 确认密码
    name: 姓名
    identity: 身份证
    alipay: 支付宝
    status: 认证状态
    level: 等级
    inviter: 邀请者
  roles: &3
    class_name: Role
    super_admin: 超级管理员
    buyer: 客户信息管理
    tax_category: 商品税收分类编码库管理
    invoice: 发票管理
  permissions: &4
    super_admin: 管理系统所有资源
  citrines: &5
    exchange_max: 300
    count: 可用茶晶
    total: 茶晶总数
  awards: &6
    ten_citrine: 10
    one_citrine: 1
  wares: &7
    title: 宝贝标题
    price: 价格
    citrine_count: 赠送茶晶数
    freight: 运费
    description: 宝贝详情
    category: 分类
    brand: 品牌
    up: 1
    up_title: 上架
    down: 0
    down_title: 下架
  trees: &8
    name: 名字
    count: 茶树数量
  leafs: &9
    produce_max: 12
    pick: 已采摘
    unpick: 未采摘
    count: 茶叶数量
    pick_time: 采摘时间
    disable: 0
    enable: 1
  orders: &10
    category_none: none
    category_recharge: 账户充值
    paid: paid
    completed: completed
    state_none: 0
    state_trade_created: 1
    state_trade_success: 2
    state_trade_failed: 3
    state_none_string: 未定义
    state_trade_created_string: 已创建
    state_trade_success_string: 支付成功
    state_trade_failed_string: 支付失败
  accounts: &11
    coin: 金额
    password: 安全密码
    number: 卡号
    award_sign_up: 10
    award_check_in: 5
    award_share: 30
    award_invite_sign_up: 10
    award_invite_recharge: 40
    enable: enable
    disable: disable
  consumes: &12
    number: 消费编号
    category: 项目
    coin_cost: 消费
    coin_now: 余额
    status: 状态
    category_none: none
    category_recharge: 充值
    category_purchase_leaf: 求购茶叶
    category_exchange_tree: 兑换茶树
    category_buy_ware: 购买茶叶商品
    category_buy_ware_citrine: 购买商品奖励茶晶
    category_buy_commision: 佣金奖励
    category_friend_reg: 好友注册赠送
    category_friend_authc: 下级实名赠送
    category_system_citrine: 系统赠送
    status_none: none
    status_create: create
    status_success: success
    status_failed: failed
    status_exception: exception
  demands: &13
    price: 单价
    count: 数量
    enable: enable
    disable: disable
  sells: &14
    price: 单价
    count: 数量
    enable: enable
    disable: disable
  systems: &15
    poundage: 0.1
    commision: 0.1
    authc_pay: 1
    default_num: 0
    default_str: '' 
    host: www.cygangsta.com
    status_en_yes: true
    status_en_no: false
    status_yes: 是
    status_no: 否
    status_public: '1'
    status_private: '0'
    default_str: ''
    default_num: 0
    default_boolean: true
    index: index
    new: new
    show: show
    delete: delete
    edit: edit
    btn_back: 返回
    btn_next: 下一步
    btn_edit: 编辑
    btn_new: 添加
    btn_show: 详情
    btn_delete: 删除
    btn_save: 保存
    company_name: 徽卅科技
    nav_item1: 首页
    nav_item2: 招标公告
    nav_item3: 中标公告
    nav_item4: 证书备案
    nav_item5: 资料系统
    opening: 新用户
    pending: 待审核
    rejected: 不通过
    passed: 通过
  trade_orders: &16
    number: 订单编号
    price: 价格
    state: 状态
    name: 姓名
    phone: 电话
    address: 地址
    wayno: 物流信息
    opening: opening
    opening_title: 新建
    pending: pending
    pending_title: 待支付
    paid: paid
    paid_title: 已支付,待发货
    departed: departed
    departed_title: 已发货
    completed: completed
    completed_title: 已完成
    canceled: canceled
    canceled_title: 已取消
  extract_cashes: &17
    coin: 提取金额
    status: 状态
    pending: pending
    pending_title: 待审核
    agree: agree
    agree_title: 同意
    disagree: disagree
    disagree_title: 不同意
  share_pools: &18
    today_enter: 今日入账
    total: 月分红池总额度
    user_total: 昨日分红池总额
    pay: 昨日白银茶主平均分红
    ware_total: 昨日黄金茶主平均分红
    gross_sale: 昨日铂金茶主平均分红
    diamond: 昨日钻石茶主平均分红
    current_total: 分红池当月总额
    own_tea: 持茶/片所得
  pick_records: &19
    number: 数量
  trades: &20
    min: 交易最低价
    max: 交易最高价
    total_purchase: 今日总求购
    price: 今日茶叶价
    volume: 今日成交量
    start: 交易开始时间
    end: 交易结束时间
    start_default: '09:00'
    end_default: '16:00'
  levels: &21
    bronze: 青铜茶主
    silver: 白银茶主
    gold: 黄金茶主
    platinum: 铂金茶主
    diamond: 钻石茶主
  teams: &22
    children: 我的直推
  tea_prices: &23
    price: 今日茶叶价
  notices: &24
    tag: 公示公告
    title: 标题
    content: 内容
  labs: &25
    tag: 公司概况
    title: 标题
    content: 内容
    order: 顺序
  members: &26
    tag: 人员队伍
    name: 姓名
    email: 邮箱
    homepage: 个人主页
    intro: 个人简介
    level: 职称
    photo: 头像
  results: &27
    tag: 业务办理 
    title: 标题
    content: 正文
    order: 顺序
  reports: &28
    tag: 水务新闻 
    title: 标题
    content: 正文
    category: 分类
    ctg_cstr: 企业建设
    ctg_serv: 服务宣传
    ctg_know: 生活常识
  activities: &29
    tag: 党建要闻
    title: 标题
    category: 分类
    content: 正文
    ctg_cmpt: 公司党建
    ctg_org: 党建和组织工作
    ctg_base: 基层党组织建设
    ctg_meb: 党员队伍建设
  manages: &30
    tag: 联系我们 
    title: 标题
    content: 正文
  meter_reads: &31
    label: 抄收绩效考核
    std_sm_wm: 小表标准 (元/块)
    std_big_wm: 大表标准 (元/块)
    std_sm_yc: 远传小表标准 (元/块)
    std_big_yc: 远传大表标准 (元/块)
    std_vst_wm: 上门催收或收费标准 (元/块)
    act_sm_read: 小表实际抄表数(不含远传表和上门收费)
    mst_sm_read: 小表应抄表数(不含远传表和上门收费)
    act_big_read: 大表实际抄表数(不含远传表和上门收费)
    mst_big_read: 大表应抄表数(不含远传表和上门收费)
    act_vst_read: 上门收费实际抄表数
    mst_vst_read: 上门收费应抄表数
    act_smyc_read: 小表远传表实际抄表数(人工抄表)
    mst_smyc_read: 小表远传表应抄表数(人工抄表)
    act_bigyc_read: 大表远传表实际抄表数(人工抄表)
    mst_bigyc_read: 大表远传表应抄表数(人工抄表)
    rcv_count: 系统中已回收水量
    wtr_count: 系统中总水量
    smp_fc_count: 抽样复查抄表准确数量
    smp_count: 抽样复查的总数量
    name: 姓名
    cal_date: 统计月份
development:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  citrines: *5
  awards: *6
  wares: *7
  trees: *8
  leafs: *9
  notices: *24
  orders: *10
  accounts: *11
  consumes: *12
  demands: *13
  sells: *14
  systems: *15
  trade_orders: *16
  extract_cashes: *17
  share_pools: *18
  pick_records: *19
  trades: *20
  levels: *21
  teams: *22
  tea_prices: *23
  labs: *25
  members: *26
  results: *27
  reports: *28
  activities: *29
  manages: *30
  meter_reads: *31
test:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  citrines: *5
  awards: *6
  wares: *7
  trees: *8
  leafs: *9
  notices: *24
  orders: *10
  accounts: *11
  consumes: *12
  demands: *13
  sells: *14
  systems: *15
  trade_orders: *16
  extract_cashes: *17
  share_pools: *18
  pick_records: *19
  trades: *20
  levels: *21
  teams: *22
  tea_prices: *23
  labs: *25
  members: *26
  results: *27
  reports: *28
  activities: *29
  manages: *30
  meter_reads: *31
production:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  citrines: *5
  awards: *6
  wares: *7
  trees: *8
  leafs: *9
  notices: *24
  orders: *10
  accounts: *11
  consumes: *12
  demands: *13
  sells: *14
  systems: *15
  trade_orders: *16
  extract_cashes: *17
  share_pools: *18
  pick_records: *19
  trades: *20
  levels: *21
  teams: *22
  tea_prices: *23
  labs: *25
  members: *26
  results: *27
  reports: *28
  activities: *29
  manages: *30
  meter_reads: *31
